//todo refactor tech component list, so the view is reusable for both tech components, usecases and services ...
// could we just add tabs in the view, and change what is shown?
// usecases should they have their own component, like technology? (then tech will include usecases as child components)