sudo: required

services:
  - docker

dist: trusty

env:
  COMPOSE_VERSION: 1.22.0

os:
  - linux

before_install:
  - pip install --user codecov

before_script:

script:
  - make build

after_success:
- codecov
