sudo: required

services:
  - docker

dist: xenial
addons:
  apt:
    packages:
    - docker

cache: npm

env:
  COMPOSE_VERSION: 1.22.0

os:
  - linux

before_install:
  - pip install --user codecov

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull mathmagicians/kumori-build:latest

script:
# Build backend
   - cd meritocracy/backend/postgres && make -f Makefile build && cd ../../../
# Build Frontend
   - cd meritocracy/frontend && make -f Makefile server_start setup build server_stop && cd ../../
# Configure environment
   - cp meritocracy/.env.sample .env
# Start Environment
   - docker-compose -f meritocracy/docker-compose.yml up -d
# Run test
   - cd meritocracy/frontend && make -f Makefile server_start rest unit server_stop && ../../
   - cd meritocracy/spec && ./gradlew && ../../
# Stop Environment
   - docker-compose  -f meritocracy/docker-compose.yml down
# Run Sonarqube scan
   - if [ "$TRAVIS_BRANCH" = "master" ]; then make sonar; fi
# Push to dockerhub
   - if [ "$TRAVIS_BRANCH" = "master" ]; then make push; fi

after_success:
- codecov
