sudo: required

services:
  - docker

dist: xenial
addons:
  apt:
    packages:
    - docker

cache: npm

env:
  COMPOSE_VERSION: 1.22.0

os:
  - linux

before_install:
  - pip install --user codecov

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull mathmagicians/kumori_build:latest

script:
# Build backend
   - make build
# Configure and start environment
   - cp .env.sample .env
   - docker-compose -f kumori.prod.yml up -d
# Run tests
   - make test
   - make jmeter
# Stop Environment
   - docker-compose -f kumori..prod.yml down
# Run Sonarqube scan
   - if [ "$TRAVIS_BRANCH" == "master" ]; then make sonar-scan; fi
# Push to dockerhub
   - if [ "$TRAVIS_BRANCH" == "master" ]; then ./release.sh --publish; fi
# Create release on github
   - if [ "$TRAVIS_BRANCH" == "master" ]; then docker run -e GITHUB_TOKEN -e TRAVIS_BUILD_NUMBER --rm -v ${PWD}:/tmp -w /tmp  mathmagicians/kumori_build:latest ./release.sh --create; fi

after_success:
- codecov
