sudo: required

services:
  - docker

dist: xenial
addons:
  apt:
    packages:
    - docker

cache: npm

env:
  COMPOSE_VERSION: 1.22.0

os:
  - linux

before_install:
  - pip install --user codecov

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull mathmagicians/kumori-build:latest

script:
# Build backend
   - cd meritocracy/backend/postgres && make -f Makefile build && cd ../../../
# Start build container
   - cd meritocracy/frontend && make -f Makefile server_start && cd ../../
# Build Frontend
   - cd meritocracy/frontend && make -f Makefile setup build && cd ../../
# Run frontend unit test
   - cd meritocracy/frontend && make -f Makefile unit && cd ../../
# Stop build container
   - cd meritocracy/frontend && make -f Makefile server_stop && cd ../../
# Configure and start environment
   - cd meritocracy
   - cp .env.sample .env
   - docker-compose -f docker-compose.yml up -d
   - cd ../
# Load fixture
   - cd meritocracy/backend
   - ./load_fixture.sh
   - cd ../..
# Run integration tests
   - meritocracy/backend/rest_test.sh eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiZWRpdG9yIn0.tYUlheVyisdr0ezFYf92mC_dvSS02cpDvPBu9aKLySk http://localhost:3000
   - cd meritocracy
   - docker-compose -f meritocracy/docker-compose.yml exec integration bash -c 'cd spec && ./gradlew'
   - cd ../
# Stop Environment
   - cd meritocracy
   - docker-compose  -f docker-compose.yml down
   - cd ../
# Run Sonarqube scan
   - if [ "$TRAVIS_BRANCH" = "master" ]; then make sonar-scan; fi
# Push to dockerhub
   - if [ "$TRAVIS_BRANCH" = "master" ]; then ./release.sh --publish; fi
# Create release on github
   - if [ "$TRAVIS_BRANCH" = "master" ]; then docker run -e GITHUB_TOKEN -e TRAVIS_BUILD_NUMBER --rm -v ${PWD}:/tmp -w /tmp  mathmagicians/kumori-build:latest ./release.sh --create; fi

after_success:
- codecov
