language: java

dist: trusty

sudo: required

os:
  - linux

jdk:
  - oraclejdk8

before_install:
  - pip install --user codecov

before_script:
  - cd ./backend && make build test

script:
  - ./gradlew

after_success:
- codecov
