sudo: required

services:
  - docker

dist: trusty

env:
  COMPOSE_VERSION: 1.22.0

os:
  - linux

before_install:
  - pip install --user codecov

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
#  - make build
#  - if [ "$TRAVIS_BRANCH" = "master" ]; then make push; fi
  - cp meritocracy/.env.sample .env
  - ls -la
  - docker-compose -f meritocracy/docker-compose.yml up -d
#  - make test
  - docker-compose down

after_success:
- codecov
