version: '2.0'
services:
  integration:
    container_name: kumori-integration
    image: mathmagicians/kumori_build
    command: ["tail", "-F", "README.md"]
    working_dir: /tmp
    volumes:
      - "./:/tmp"
    networks:
      - kumori

  web:
    container_name: kumori-web
    image: mathmagicians/kumori_web:${VERSION}
    ports:
      - "80:80"
    networks:
      - kumori
    restart: unless-stopped

  postgrest:
    container_name: kumori-postgrest
    image: postgrest/postgrest:latest
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://${POSTGREST_CONNECTION_USER}:${POSTGREST_CONNECTION_PASSWORD}@postgres:5432/${POSTGREST_CONNECTION_DB}
      PGRST_DB_SCHEMA: ${POSTGREST_CONNECTION_SCHEMA}
      PGRST_DB_ANON_ROLE: ${POSTGREST_ANON_ROLE}
      PGRST_JWT_SECRET: ${PGRST_JWT_SECRET} # Must be minimum 32 characters
    depends_on:
      - postgres
    networks:
      - kumori

  postgres:
    container_name: kumori-postgres
    image: mathmagicians/kumory_db:${VERSION}
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_SCHEMA: ${POSTGREST_CONNECTION_SCHEMA}
      DB_CRUD_USER: ${POSTGREST_CONNECTION_USER}
      DB_CRUD_PASS: ${POSTGREST_CONNECTION_PASSWORD}
      DB_R_USER: ${POSTGREST_ANON_ROLE}
    networks:
      - kumori

  swagger:
    container_name: kumori-swagger
    image: swaggerapi/swagger-ui
    ports:
      - "8070:8080"
    environment:
      API_URL: http://localhost:3000/
    depends_on:
      - postgrest
    networks:
      - kumori

networks:
  kumori:
    driver: bridge
