version: '3.5'
services:
  devserver:
    container_name: meritocracy
    image: meritocracy:latest
    ports:
      - "8080:8080"
    networks:
      - frontend

  postgrest:
    container_name: postgrest
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://meritocracy:meritocracy@postgres:5432/meritocracy
      PGRST_DB_SCHEMA: api
      PGRST_DB_ANON_ROLE: web_anon
    depends_on:
      - postgres
    networks:
      - frontend
      - backend

  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - "data-postgres:/var/lib/postgresql/data"
    networks:
      - backend

volumes:
  data-postgres:
    name: meritocracy

networks:
  frontend:
    driver: bridge
    name: frontend
  backend:
    driver: bridge
    name: backend
