version: '2.0'
services:
  devserver:
    container_name: meritocracy_${MERITOCRACY_VERSION}-devserver
    image: node
    command: ["npm", "run", "dev"]
    working_dir: /tmp
    ports:
      - "80:8080"
    volumes:
      - "./:/tmp"
    networks:
      - meritocracy

  postgrest:
    container_name: meritocracy_${MERITOCRACY_VERSION}-postgrest
    image: postgrest/postgrest:latest
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://${POSTGREST_CONNECTION_USER}:${POSTGREST_CONNECTION_PASSWORD}@postgres:5432/${POSTGREST_CONNECTION_DB}
      PGRST_DB_SCHEMA: ${POSTGREST_CONNECTION_SCHEMA}
      PGRST_DB_ANON_ROLE: ${POSTGREST_ANON_ROLE}
      PGRST_JWT_SECRET: ${PGRST_JWT_SECRET} # Must be minimum 32 characters
    depends_on:
      - postgres
    networks:
      - meritocracy

  postgres:
    container_name: meritocracy_${MERITOCRACY_VERSION}-postgres
    image: mathmagicians/meritocracy_db:latest
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_SCHEMA: ${POSTGREST_CONNECTION_SCHEMA}
      DB_CRUD_USER: ${POSTGREST_CONNECTION_USER}
      DB_CRUD_PASS: ${POSTGREST_CONNECTION_PASSWORD}
      DB_R_USER: ${POSTGREST_ANON_ROLE}
      TAXONOMY: ${TAXONOMY}
      COMPONENTS: ${COMPONENTS}
    networks:
      - meritocracy

  pgadmin:
    container_name: meritocracy_${MERITOCRACY_VERSION}-pgadmin
    image: chorss/docker-pgadmin4:latest
    ports:
    - "5050:5050"
    networks:
      - meritocracy
    volumes:
    - data-pgadmin:/data

  swagger:
    container_name: meritocracy_${MERITOCRACY_VERSION}-swagger
    image: swaggerapi/swagger-ui
    ports:
      - "8070:8080"
    environment:
      API_URL: http://localhost:3000/
    depends_on:
      - postgrest
    networks:
      - meritocracy

volumes:
  data-pgadmin:

networks:
  meritocracy:
    driver: bridge
