version: '3.5'
services:
  web:
    container_name: meritocracy_${MERITOCRACY_VERSION}-web
    image: mathmagicians/meritocracy_web:latest
    ports:
      - "80:80"
    networks:
      - meritocracy-frontend
      - meritocracy-backend
    restart: unless-stopped

  postgrest:
    container_name: meritocracy_${MERITOCRACY_VERSION}-postgrest
    image: postgrest/postgrest:latest
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://${POSTGREST_CONNECTION_USER}:${POSTGREST_CONNECTION_PASSWORD}@postgres:5432/${POSTGREST_CONNECTION_DB}
      PGRST_DB_SCHEMA: ${POSTGREST_CONNECTION_SCHEMA}
      PGRST_DB_ANON_ROLE: ${POSTGREST_ANON_ROLE}
    depends_on:
      - postgres
    networks:
      - meritocracy-frontend
      - meritocracy-backend
    restart: unless-stopped

  postgres:
    container_name: meritocracy_${MERITOCRACY_VERSION}-postgres
    image: mathmagicians/meritocracy_db:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_SCHEMA: ${POSTGREST_CONNECTION_SCHEMA}
      DB_CRUD_USER: ${POSTGREST_CONNECTION_USER}
      DB_CRUD_PASS: ${POSTGREST_CONNECTION_PASSWORD}
      DB_R_USER: ${POSTGREST_ANON_ROLE}
      TAXONOMY: ${TAXONOMY}
      COMPONENTS: ${COMPONENTS}
    networks:
      - meritocracy-backend
    restart: unless-stopped

  swagger:
    container_name: meritocracy_${MERITOCRACY_VERSION}-swagger
    image: swaggerapi/swagger-ui
    ports:
      - "8070:8080"
    environment:
      API_URL: http://localhost:3000/
    depends_on:
      - postgrest
    networks:
      - meritocracy-frontend
    restart: unless-stopped

networks:
  meritocracy-frontend:
    driver: bridge
    name: meritocracy_${MERITOCRACY_VERSION}-frontend
  meritocracy-backend:
    driver: bridge
    name: meritocracy_${MERITOCRACY_VERSION}-backend
