<template>
	<div>
		<b-alert
			v-if="!isEditOn" 
			show
			variant="danger">
			<v-icon name="times" scale="2">
			</v-icon>
			You must be logged in, and enable editing, before you can proceed.
		</b-alert>
		<b-card 
			v-else
			no-body
			>
			<b-card-header>
				Edit Technology: 
				<strong>{{techModel.name}}</strong> 
				<life-cycle :status="techModel.status"></life-cycle>
				<p>{{techModel}}</p>
				<p>{{txModel}}</p>
			</b-card-header>
			<b-card-body>
				<b-form @submit="onSubmit" @reset="onReset">
					 <b-list-group flush>
      					<b-list-group-item>
      						<h4>Basic Information</h4>
					<b-form-group id="uidGroup"
						label="ID of technology"
						label-for="uidInput"
						description="Tech ID is autogenerated">
						<b-form-input 
							id="uidInput"
							ref="uidInput"
							type="text"
							readonly
							v-model="techModel.uid"
							placeholder="tech uid is autogenerated">
						</b-form-input>
					</b-form-group>
					<b-form-row>
						<b-form-group id="nameInputGroup"
							label="Name of technology"
							label-for="nameInput"
							description="What is the name of the technology?">
							<b-form-input id="nameInput"
							type="text"
							v-model="techModel.name"
							required
							placeholder="Write tech's name">
							</b-form-input>
						</b-form-group>
						<b-form-group id="lcGroup"
							label="Lifecycle status of technology"
							label-for="lcSelect"
							description="What is the current status on #techmenu?">
							 <b-form-select 
							 	id="lcSelect" 
							 	v-model="techModel.status" 
							 	:options="lc" 
							 	class="mb-3" />
						</b-form-group>
					</b-form-row>
					<b-form-group id="nameInputGroup"
							label="Description of technology"
							label-for="nameInput"
							description="What is the name of the technology?">
						<b-form-textarea id="descText"
							v-model="techModel.description"
							placeholder="Descibe what this tech is about..."
							:rows="3"
							:max-rows="6">
						</b-form-textarea>
					</b-form-group>
				</b-list-group-item>
				<b-list-group-item>
					<h4>Classify the use case in the TBM Taxonomy</h4>
					<b-form-row>
						<b-form-group 
							v-for="(level,index) in taxonomyLevels"
							v-show="isLeftDefined(index) && treeGeneration(index).length > 0"
							:id="'txLevel_'+level"
							:label="level"
							:label-for="'txSelect_'+level">
							 <b-form-select 
							 	:id="'txSelect_'+level"
							 	v-model="txModel[level]" 
							 	:options="treeGeneration(index)"
							 	text-field="name"
							 	value-field="name"
							 	class="mb-3" />
						</b-form-group>
					</b-form-row>
				</b-list-group-item>
				<b-list-group-item>
					<h4>Specify Usecases for Technology</h4>
					<b-button
						@click="addUsecase">
						Add Usecase
					</b-button>
					<b-list-group-item
						v-for="(usecase,index) in techModel.usecases">
						<b-form-group :id="'usecaseNameInputGroup_'+index"
							label="Name of usecase"
							:label-for="'usecaseNameInput_'+index"
							description="What is the usecase for the technology?">
							<b-form-input 
								:id="'usecaseNameInput_'+index"
								type="text"
								v-model="techModel.usecases[index].name"
								required
								placeholder="Write usecase name - what problem are you trying to solve?">
							</b-form-input>
						</b-form-group>
						<b-form-group :id="'usecaseDescInputGroup_'+index"
							label="Description of usecase"
							:label-for="'usecaseDescInput_'+index"
							description="Describe, how should the technnology be used?">
							<b-form-textarea 
								:id="'usecaseDescInput_'+index"
								v-model="techModel.usecases[index].description"
								placeholder="Descibe how to use this tech ..."
								:rows="3"
								:max-rows="6">
							</b-form-textarea>
						</b-form-group>
						<b-form-group 
							:id="'usecaselcGroup_'+index"
							label="Lifecycle status of technology for this usecase"
							:label-for="'usecaselc_'+index"
							description="What is the current status of the tech for this usecase on #techmenu?">
							<b-form-row>
								<b-form-select 
								 	:id="'usecaselc_'+index" 
								 	v-model="techModel.usecases[index].status" 
								 	:options="lc" 
								 	class="mb-3" 
							 	/>
							 	<life-cycle :status="techModel.usecases[index].status"></life-cycle>
							</b-form-row>
						</b-form-group>
					</b-list-group-item>
				</b-list-group-item>
			</b-list-group>
					<b-button type="submit" variant="success">Save</b-button>
					<b-button type="reset" variant="outline-secondary">Cancel</b-button>
				</b-form>
			</b-card-body>
		</b-card>
	</div>
</template>

<script>
import LifeCycle from "../components/LifeCycle.vue";
import lifeCycleMixin from "../mixins/lifeCycle.js";

export default {
	name: "techComponentEditor",
	components: { LifeCycle },
	mixins: [lifeCycleMixin],
	data() {
		return {
			techModel: {
				uid: "",
				name: "",
				status: "",
				description: "",
				comments: [],
				tax: [],
				licenses: [],
				links: [],
				usecases: [],
				log: []
			},
			usecaseModel: {
				name: "",
				description: "",
				status: "",
				scope: ""
			},
			logModel: {
				date: "",
				description: "",
				status: ""
			},
			txModel: this.$store.getters.taxonomy.levels.reduce(
				(acc, t) => ({ ...acc, [t.name]: "" }),
				{}
			)
		};
	},
	computed: {
		isEditOn() {
			return this.$store.getters.isEditOn;
		},
		lc() {
			return this.$store.getters.lifeCycle.items.map(it => it.name);
		},
		taxonomyLevels() {
			return this.$store.getters.taxonomy.levels.map(tx => tx.name);
		},
		txTree() {
			return this.buildTree(this.$store.getters.taxonomy.tags);
		}
	},
	methods: {
		onSubmit() {
			console.log("todo submit");
		},
		onReset() {
			console.log("todo reset");
		},
		treeGeneration(n) {
			if (n === 0) return this.txTree;

			const lookup = this.taxonomyLevels[n - 1];
			const leftSelection = this.txModel[lookup];
			const myNode = this.findNodeForName(this.txModel[lookup]);
			return myNode ? myNode.children : [];
		},
		isLeftDefined(index) {
			if (index === 0) return true;

			const lookup = this.taxonomyLevels[index - 1];
			const leftSelection = this.txModel[lookup];
			return leftSelection !== null && leftSelection !== "";
		},
		findNodeForName(name) {
			const stack = [...this.txTree];
			while (stack.length) {
				const node = stack.pop();
				if (node.name === name) return node;
				stack.push(...node.children);
			}
			return null;
		},
		addUsecase(){
			this.techModel.usecases.push( {...this.useCaseModel})
		}
	}
};
</script>
