<template>
	<div>
		<b-alert
			v-if="!isEditOn" 
			show
			variant="danger">
			<v-icon name="times" scale="2">
			</v-icon>
			You must be logged in, and enable editing, before you can proceed.
		</b-alert>
		<b-card v-else>
			<b-card-header>
				Edit Technology: 
				<strong>{{techModel.name}}</strong> 
				<life-cycle :status="techModel.status"></life-cycle>
				<p>{{techModel}}</p>
				<p>{{txModel}}</p>
			</b-card-header>
			<b-card-body>
				<b-form @submit="onSubmit" @reset="onReset">
					<b-form-group id="uidGroup"
						label="ID of technology"
						label-for="uidInput"
						description="Tech ID is autogenerated">
						<b-form-input id="uidInput"
							type="text"
							readonly
							v-model="techModel.uid"
							placeholder="tech uid is autogenerated">
						</b-form-input>
					</b-form-group>
					<b-form-row>
						<b-form-group id="nameInputGroup"
							label="Name of technology"
							label-for="nameInput"
							description="What is the name of the technology?">
							<b-form-input id="nameInput"
							type="text"
							v-model="techModel.name"
							required
							placeholder="Write tech's name">
							</b-form-input>
						</b-form-group>
						<b-form-group id="lcGroup"
							label="Lifecycle status of technology"
							label-for="lcSelect"
							description="What is the current status on #techmenu?">
							 <b-form-select 
							 	id="lcSelect" 
							 	v-model="techModel.status" 
							 	:options="lc" 
							 	class="mb-3" />
						</b-form-group>
					</b-form-row>
					<b-form-group id="nameInputGroup"
							label="Description of technology"
							label-for="nameInput"
							description="What is the name of the technology?">
						<b-form-textarea id="descText"
							v-model="techModel.description"
							placeholder="Descibe what this tech is about..."
							:rows="3"
							:max-rows="6">
						</b-form-textarea>
					</b-form-group>
					<b-form-row>
						<b-form-group 
							v-for="level in taxonomyLevels"
							:id="'txLevel_'+level"
							:label="level"
							:label-for="'txSelect_'+level">
							 <b-form-select 
							 	:id="'txSelect_'+level" 
							 	v-model="txModel[level]" 
							 	:options="lc" 
							 	class="mb-3" />
						</b-form-group>
					</b-form-row>
					<b-button type="submit" variant="success">Save</b-button>
					<b-button type="reset" variant="outline-secondary">Cancel</b-button>
				</b-form>
			</b-card-body>
		</b-card>
	</div>
</template>

<script>
	import LifeCycle from '../components/LifeCycle.vue'
	import lifeCycleMixin from '../mixins/lifeCycle.js'
  	

	export default {
		name: "techComponentEditor",
		components: {LifeCycle},
		mixins: [
			lifeCycleMixin
		],
		data(){
			return {
				techModel: {
					uid: '',
					name: '',
					status: '',
					description: '',
					comments: [],
					tax: [],
					licenses: [],
					links: [],
					usecases: [],
					log: []
				},
				usecaseModel: {
					name: '',
					description: '',
					status: '',
					scope: ''
				},
				logModel: {
					date: '',
					description: '',
					status: ''
				},
				txModel: this.$store.state.taxonomy.levels.reduce( (acc, t) => ({...acc, [t.name]: false}), {}),
			}
		},
		computed: {
			isEditOn() {
        		return this.$store.getters.isEditOn;
      		},
      		lc() {
      			return this.$store.state.lifeCycle.items.map( it => it.name);
      		},
      		taxonomyLevels(){
      			return this.$store.state.taxonomy.levels.map( tx => tx.name);
      		}
		},
		methods: {
			onSubmit(){
				console.log("todo submit");
			},
			onReset(){
				console.log("todo reset");
			}
		}
	}

</script>