<template>
	<div :id="'edit_'+uid">
		<b-alert
			v-if="!isEditOn" 
			show
			variant="danger">
			<v-icon name="times" scale="2">
			</v-icon>
			You must be logged in, and enable editing, before you can proceed.
			<p>{{techModel}}</p>
		</b-alert>
		<b-card 
			:id="'editor_'+uid"
			v-else
			no-body
			>
			<b-card-header
				:id="'editor_header_'+uid">
				Edit Technology: 
				<strong>{{techModel.name}}</strong> 
				<life-cycle :status="techModel.status"></life-cycle>
				<p>{{techModel}}</p>
				<p>{{txModel}}</p>
			</b-card-header>
			<b-card-body
				:id="'editor_body_'+uid">
				<b-form 
					:id="'editor_form_'+uid"
					@submit.prevent="onSubmit" 
					@reset.prevent="onReset">
					 <b-list-group flush>
      					<b-list-group-item>
      						<h4>Basic Information</h4>
							<b-form-group 
								:id="'uidGroup_'+uid"
								label="ID of technology"
								label-for="uidInput"
								description="Tech ID is autogenerated">
								<b-form-input 
									:id="'uidInput_'+uid"
									ref="uidInput"
									type="text"
									readonly
									v-model="techModel.uid"
									placeholder="tech uid is autogenerated">
								</b-form-input>
							</b-form-group>
							<b-form-row>
								<b-form-group id="nameInputGroup"
									label="Name of technology"
									label-for="nameInput"
									description="What is the name of the technology?">
									<b-form-input id="nameInput"
									type="text"
									v-model="techModel.name"
									required
									placeholder="Write tech's name">
									</b-form-input>
								</b-form-group>
								<b-form-group id="lcGroup"
									label="Lifecycle status of technology"
									label-for="lcSelect"
									description="What is the current status on #techmenu?">
									 <b-form-select 
									 	id="lcSelect" 
									 	v-model="techModel.status" 
									 	:options="lc" 
									 	class="mb-3" />
								</b-form-group>
							</b-form-row>
							<b-form-group id="nameInputGroup"
									label="Description of technology"
									label-for="nameInput"
									description="What is the name of the technology?">
								<b-form-textarea id="descText"
									v-model="techModel.description"
									placeholder="Descibe what this tech is about..."
									:rows="3"
									:max-rows="6">
								</b-form-textarea>
							</b-form-group>
						</b-list-group-item>
						<b-list-group-item>
							<h4>Classify the use case in the TBM Taxonomy</h4>
							<b-form-row>
								<b-form-group 
									v-for="(level,index) in taxonomyLevels"
									v-show="isLeftDefined(index) && treeGeneration(index).length > 0"
									:id="'txLevel_'+level"
									:label="level"
									:label-for="'txSelect_'+level">
									 <b-form-select 
									 	:id="'txSelect_'+level"
									 	v-model="txModel[level]" 
									 	:options="treeGeneration(index)"
									 	text-field="name"
									 	value-field="name"
									 	@change="updateTax"
									 	class="mb-3" />
								</b-form-group>
							</b-form-row>
						</b-list-group-item>
						<b-list-group-item>
							<h4>Specify Usecases for Technology</h4>
							<b-button
								@click="addUsecase">
								Add Usecase
							</b-button>
							<b-list-group-item
								v-for="(usecase,index) in techModel.usecases">
								<b-form-group :id="'usecaseNameInputGroup_'+index"
									label="Name of usecase"
									:label-for="'usecaseNameInput_'+index"
									description="What is the usecase for the technology?">
									<b-form-input 
										:id="'usecaseNameInput_'+index"
										type="text"
										v-model="techModel.usecases[index].name"
										required
										placeholder="Write usecase name - what problem are you trying to solve?">
									</b-form-input>
								</b-form-group>
								<b-form-group :id="'usecaseDescInputGroup_'+index"
									label="Description of usecase"
									:label-for="'usecaseDescInput_'+index"
									description="Describe, how should the technnology be used?">
									<b-form-textarea 
										:id="'usecaseDescInput_'+index"
										v-model="techModel.usecases[index].description"
										placeholder="Descibe how to use this tech ..."
										:rows="3"
										:max-rows="6">
									</b-form-textarea>
								</b-form-group>
								<b-form-group 
									:id="'usecaselcGroup_'+index"
									label="Lifecycle status of technology for this usecase"
									:label-for="'usecaselc_'+index"
									description="What is the current status of the tech for this usecase on #techmenu?">
									<b-form-row>
										<b-form-select 
										 	:id="'usecaselc_'+index" 
										 	v-model="techModel.usecases[index].status" 
										 	:options="lc" 
										 	class="mb-3" 
									 	/>
									 	<life-cycle :status="techModel.usecases[index].status"></life-cycle>
									</b-form-row>
								</b-form-group>
							</b-list-group-item>
						</b-list-group-item>
						<b-list-group-item 
							v-if="techModel.log"
							v-for="entry in techModel.log">
							<v-icon name="play"/>
							{{entry.date}}: {{entry.description}} 
							<life-cycle :status="entry.status"/>
						</b-list-group-item>
					</b-list-group>
					<b-button type="submit" variant="success">Save</b-button>
					<b-button type="reset" variant="outline-secondary">Cancel</b-button>
				</b-form>
			</b-card-body>
		</b-card>
	</div>
</template>

<script>
import LifeCycle from "../components/LifeCycle.vue";
import lifeCycleMixin from "../mixins/lifeCycle.js";

export default {
	name: "techComponentEditor",
	components: { LifeCycle },
	mixins: [lifeCycleMixin],
	props: {
	    uid: {
	      type: String,
	      default: ''
	    }
	},
	data() {
		return {
			techModel:  {
				uid: "",
				name: "",
				status: "",
				description: "",
				comments: [],
				tags: [],
				licenses: [],
				links: [],
				usecases: [],
				log: []
			},
			usecaseModel: {
				name: "",
				description: "",
				status: "",
				scope: ""
			},
			logModel: {
				date: "",
				description: "",
				status: "",
				who:""
			},
			txModel: {}
		};
	},
	computed: {
		isEditOn() {
			return this.$store.getters.isEditOn;
		},
		lc() {
			return this.$store.getters.lifeCycle.items.map(it => it.name);
		},
		taxonomyLevels() {
			return this.$store.getters.taxonomy.levels.map(tx => tx.name);
		},
		txTree() {
			return this.buildTree(this.$store.getters.taxonomy.tags);
		}
	},
	created() {
		this.txModel =this.taxonomyLevels.reduce(
				(acc, t) => ({ ...acc, [t]: "" }), {} ) 
		let myTech = this.$store.getters.tech.filter( tech => tech.uid === this.uid ).pop()
		this.techModel = {...this.techModel,...myTech} 
		//let myTax = this.techModel.tax
		this.techModel.tags.forEach( 
				tag =>  this.txModel[this.taxonomyLevels[this.findNodeForName(tag).level -1]] = tag 
		)
	},
	methods: {
		onSubmit() {
			console.log("todo submit")
		},
		onReset() {
			//pop back to calling component
			this.$router.go(-1)
		},
		/* Finds next generation in a tree at the level of leaf #n */
		treeGeneration(n) {
			if (n === 0) return this.txTree;
			const lookup = this.taxonomyLevels[n - 1];
			const leftSelection = this.txModel[lookup];
			const myNode = this.findNodeForName(this.txModel[lookup]);
			return myNode ? myNode.children : [];
		},
		/** Checks if the txModel has the parent (left) defined */
		isLeftDefined(index) {
			if (index === 0) return true;
			const lookup = this.taxonomyLevels[index - 1];
			const leftSelection = this.txModel[lookup];
			return leftSelection !== null && leftSelection !== "";
		},
		/* Finds node in taxonomy tree with the given name */
		findNodeForName(name) {
			const stack = [...this.txTree];
			while (stack.length) {
				const node = stack.pop();
				if (node.name === name) return node;
				stack.push(...node.children);
			}
			return null;
		},
		addUsecase(){
			this.techModel.usecases.push( {...this.useCaseModel})
		},
		updateTax(){
			console.log("Updating tags")
			let newTags = Object.values(this.txModel).filter( tx => tx && tx !== '' && tx !== undefined)
			console.log(newTags)
			this.techModel.tags = newTags
			console.log(this.techModel.tags)
			
		}
	}
};
</script>
