version: '3'
services:
  grafana:
    container_name: kumori-grafana
    image: grafana/grafana
    ports:
    - "3000:3000"
    networks:
    - frontend
    - backend
    depends_on:
    - postgres
    links:
    - postgres
    environment:
      GF_INSTALL_PLUGINS: digrich-bubblechart-panel,savantly-heatmap-panel
    volumes:
    - grafana:/var/lib/grafana
  postgres:
    container_name: kumori-postgres
    image: postgres:alpine
    networks:
      - backend
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
    - postgres:/var/lib/postgresql/data
  pgadmin:
    container_name: kumori-pgadmin
    image: chorss/docker-pgadmin4:latest
    ports:
    - "5050:5050"
    networks:
      - frontend
      - backend
    volumes:
    - pgadmin:/data
  tensorflow:
    container_name: kumori-tensorflow
    image: tensorflow/tensorflow:latest
    ports:
    - "8888:8888"
    networks:
    - frontend
    - backend
  neo4j:
    container_name: kumori-neo4j
    image: neo4j:latest
    ports:
    - "7474:7474"
    - "7687:7687"
    networks:
    - frontend
    - backend
    environment:
      NEO4J_AUTH: none
    volumes:
    - neo4j:/data
  sonarqube:
    container_name: kumori-sonarqube
    image: sonarqube:latest
    ports:
    - "9000:9000"
    - "9092:9092"
    networks:
    - frontend
    - backend
    volumes:
    - sonarqube:/opt/sonarqube
    depends_on:
    - postgres
    environment:
      SONARQUBE_JDBC_USERNAME: sonarqube
      SONARQUBE_JDBC_PASSWORD: sonarqube
      SONARQUBE_JDBC_URL: jdbc:postgresql://postgres/sonarqube
  confluence:
    container_name: kumori-confluence
    image: atlassian/confluence-server
    ports:
     - "8090:8090"
    networks:
    - frontend
    volumes:
    - confluence:/var/atlassian/application-data/confluence
    depends_on:
    - postgres
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  postgres:
  sonarqube:
  confluence:
  neo4j:
  pgadmin:
  grafana:
