version: '3'
services:
  sonarqube:
    container_name: sonarqube
    image: sonarqube:latest
    ports:
    - "80:9000"
    - "9092:9092"
    volumes:
    - sonarqube:/opt/sonarqube
    depends_on:
    - postgres
    environment:
      SONARQUBE_JDBC_USERNAME: sonarqube
      SONARQUBE_JDBC_PASSWORD: sonarqube
      SONARQUBE_JDBC_URL: jdbc:postgresql://postgres/sonarqube

  postgres:
    container_name: postgres
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: sonarqube
      POSTGRES_USER: sonarqube
      POSTGRES_DB:   sonarqube
    volumes:
    - postgres:/var/lib/postgresql/data

volumes:
  postgres:
  sonarqube:
